import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * The six top-level categories are fixed and shared across all five
 * warehouse-systems documentation sites, in this order:
 * Overview, Business Context, Domain-Driven Design, API Reference,
 * Ecosystem, Architecture Decision Records.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/introduction'},
      items: ['overview/architecture', 'overview/quickstart'],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/domain-vision'},
      items: [
        'business-context/ubiquitous-language',
        'business-context/chaotic-storage',
        'business-context/revocable-reservations',
        'business-context/usable-inventory',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/ddd-artifacts'},
      items: [
        'ddd/subdomain-classification',
        'ddd/core-domain-chart',
        'ddd/bounded-context-canvas',
        'ddd/aggregate-design-canvas',
        'ddd/domain-events',
        'ddd/domain-message-flow',
        'ddd/eventstorming',
        'ddd/use-cases',
        'ddd/class-diagram',
        'ddd/entity-relationship',
        'ddd/sequence-diagrams',
        'ddd/context-relationships',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar, 'api-reference/events'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/context-map'},
      items: ['ecosystem/integration'],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      collapsed: false,
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics (Data Product)',
      collapsed: false,
      items: ['analytics/inventory-flow-accuracy-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/about'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-chaotic-storage-over-fixed-slotting',
        'adr/0003-revocable-reservations',
        'adr/0004-kafka-integration-events',
        'adr/0005-rfc-7807-problem-details',
        'adr/0006-arch-go-fitness-tests',
        'adr/0007-godog-bdd-acceptance-tests',
        'adr/0008-mcp-inbound-adapter',
        'adr/0009-product-classification-as-sku-master-data',
        'adr/0010-dot-hazard-class-and-same-bin-segregation',
        'adr/0011-analytical-data-product',
        'adr/0012-adopt-mfe-console-architecture',
        'adr/0013-location-classification-via-facility-events',
        'adr/0014-rest-identity-adoption',
        'adr/0015-remove-rest-identity-layer',
        'adr/0016-standard-metrics-convention',
        'adr/0017-transactional-outbox',
        'adr/0018-idempotency-key-middleware',
        'adr/0019-optimistic-concurrency-version-column',
        'adr/0020-resilience-circuit-breaker-retry-dlq-shutdown',
        'adr/0021-kafka-producer-partition-key',
        'adr/0022-horizontal-autoscaling-and-pgxpool-tuning',
        'adr/0023-migrations-direct-postgres-connection',
        'adr/0024-cloudevents-mandatory-envelope',
        'adr/0025-bin-registration-endpoint-and-pick-location',
        'adr/0026-housekeeping-sweeper-idempotency-keys-and-outbox',
        'adr/0027-mcp-eval-and-governance-suite',
        'adr/0028-bootretry-boot-time-dial-retry',
        'adr/0029-extra-architecture-fitness-tests',
        'adr/0030-site-scoped-transfer-allocation',
        'adr/0031-publish-product-classified',
        'adr/0032-confirm-pick-event-driven',
        'adr/0033-destination-transfer-receipt-custody',
        'adr/0034-product-master-owns-classification',
        'adr/0035-confirm-pick-from-task-completed',
        'adr/0036-per-line-confirm-pick',
        'adr/0037-stock-receipts-from-inbound-receiving',
      ],
    },
  ],
};

export default sidebars;
